# Generated by Django 6.0 on 2025-12-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image_url', models.URLField(verbose_name='URL изображения')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('duration', models.IntegerField(choices=[(5, '5 дней'), (7, '7 дней'), (10, '10 дней'), (14, '14 дней'), (21, '21 день')], verbose_name='Длительность')),
                ('popularity', models.IntegerField(default=0, verbose_name='Популярность')),
                ('tags', models.CharField(help_text='Разделяйте теги запятой', max_length=500, verbose_name='Теги')),
                ('destination_type', models.CharField(choices=[('ny', 'Нью-Йорк'), ('west', 'Запад США'), ('fl', 'Флорида'), ('custom', 'Индивидуальный')], max_length=50, verbose_name='Тип направления')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
    ]
